services:
  web:
    build:
      context: .
    container_name: hello-flask
    ports:
      - "8080:80"
    volumes:                
      - /home/d1ko4/logs/app:/app/logs
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
